# Uncomment the next line to define a global platform for your project

platform :ios, '9.0'

target 'Demo-iOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Demo-iOS
  pod 'ThreeSixtyPlayer', :path => '../'

  target 'Demo-iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Demo-iOSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
